-- seed data for the clinical trial dashboard
-- this file is executed after all migrations on `supabase start` and `supabase db reset`.
--
-- Event model, Stage 1 (data foundation): the old marker/event system taxonomy and
-- the demo bootstrap were removed here. The unified event_type_categories and
-- event_types now ship as system rows inside their migrations, so no seed is needed
-- for them. The demo space (companies, trials, events, intelligence) is reintroduced
-- in Stage 4 when seed_demo_data and the producers are repointed at the Event model.
-- Integration tests build their own personas/spaces and do not depend on this file.
