-- Task A0: Schema prerequisites for event-model cutover
--
-- 1. primary_intelligence_links entity_type check: swap 'marker' -> 'event'
-- 2. trial_change_events: rename marker_id -> event_id, add FK to events, drop index, new index
-- 3. trial_change_events: drop derived_from_marker_change_id (marker_changes log is gone;
--    event_changes from Stage 1 replaces it)
--
-- Pre-check (verified at authoring time, 2026-06-28):
--   select count(*) from public.primary_intelligence_links where entity_type='marker'; -> 0
-- No rows exist with entity_type='marker', so the constraint swap is non-destructive.

-- ############################################################
-- 1. primary_intelligence_links entity_type check constraint
-- ############################################################

-- Runtime guard: fail with a clear message if any 'marker' rows still exist
-- (greenfield expects zero) instead of an opaque check-constraint violation.
do $$ begin
  if exists (select 1 from public.primary_intelligence_links where entity_type = 'marker') then
    raise exception 'entity_type=marker rows exist; cannot swap constraint to event until they are migrated';
  end if;
end $$;

alter table public.primary_intelligence_links
  drop constraint primary_intelligence_links_entity_type_check;

alter table public.primary_intelligence_links
  add constraint primary_intelligence_links_entity_type_check
    check (entity_type = any (array[
      'trial'::text,
      'event'::text,
      'company'::text,
      'asset'::text,
      'product'::text
    ]));

-- ############################################################
-- 2. trial_change_events: marker_id -> event_id with FK
-- ############################################################

-- Drop the partial index on marker_id before renaming
drop index if exists public.idx_change_events_marker;

-- Rename the column
alter table public.trial_change_events
  rename column marker_id to event_id;

-- Greenfield cutover (no backfill): a non-fresh database (dev/prod) carries
-- pre-cutover trial_change_events rows whose former marker_id (now event_id)
-- references markers dropped by this cutover and absent from the new events
-- table. Discard the dangling rows so the new FK validates. The detected-change
-- history is regenerated by CT.gov ingest under the unified model. On a fresh
-- db reset this is a no-op (the table is empty). The FK is on delete set null,
-- but we delete rather than null because a marker-anchored change row has no
-- meaning once its marker is gone.
delete from public.trial_change_events
  where event_id is not null
    and not exists (
      select 1 from public.events e where e.id = public.trial_change_events.event_id
    );

-- Add FK to events
alter table public.trial_change_events
  add constraint trial_change_events_event_id_fkey
    foreign key (event_id) references public.events(id) on delete set null;

-- Recreate partial index under the new column name
create index idx_change_events_event
  on public.trial_change_events (event_id)
  where event_id is not null;

-- ############################################################
-- 3. trial_change_events: drop derived_from_marker_change_id
-- ############################################################

alter table public.trial_change_events
  drop column if exists derived_from_marker_change_id;

-- ############################################################
-- Smoke: insert a primary_intelligence_links row with entity_type='event'
-- Scratch scaffold (user + tenant + space + event) created and torn down here.
-- seed.sql has not run at migration time, so we cannot rely on demo data.
-- Pattern mirrors 20260428042300 (whitelabel isolation smoke). The system
-- event_type from 20260628071012 (a0000000-...-000011) is available because
-- that migration runs before this one.
-- ############################################################
do $$
declare
  v_event_type_id uuid := 'a0000000-0000-0000-0000-000000000011';
  v_user_id       uuid;
  v_tenant_id     uuid;
  v_space_id      uuid;
  v_event_id      uuid;
  v_anchor_id     uuid;
  v_pi_id         uuid;
  v_link_id       uuid;
begin
  -- Scratch auth user (only id is required; all other columns nullable)
  insert into auth.users (id, email)
  values (gen_random_uuid(), '_smoke_a0_' || substr(gen_random_uuid()::text, 1, 8) || '@smoke.test')
  returning id into v_user_id;

  -- Scratch tenant
  insert into public.tenants (name, slug)
  values ('_smoke_A0_tenant_', '_smoke-a0-' || substr(v_user_id::text, 1, 8))
  returning id into v_tenant_id;

  -- Scratch space in that tenant, owned by the scratch user
  insert into public.spaces (tenant_id, name, created_by)
  values (v_tenant_id, '_smoke_A0_space_', v_user_id)
  returning id into v_space_id;

  -- Space-anchored scratch event (anchor_type='space' does not require anchor_id).
  -- The events_audit trigger logs to event_changes with this space_id; the
  -- space now exists, so the FK is satisfied.
  insert into public.events
    (space_id, event_type_id, title, event_date, anchor_type, created_by)
  values
    (v_space_id, v_event_type_id, '_smoke_A0_event_', current_date, 'space', v_user_id)
  returning id into v_event_id;

  -- Scratch PI anchor (entity_id has no FK; use a random UUID as placeholder)
  insert into public.primary_intelligence_anchors (space_id, entity_type, entity_id, is_lead)
  values (v_space_id, 'trial', gen_random_uuid(), false)
  returning id into v_anchor_id;

  -- Scratch primary_intelligence (draft avoids version-number trigger logic)
  insert into public.primary_intelligence
    (space_id, state, headline, summary_md, implications_md, last_edited_by, anchor_id)
  values (v_space_id, 'draft', '_smoke_A0_pi_', '', '', v_user_id, v_anchor_id)
  returning id into v_pi_id;

  -- Insert link with entity_type='event' (the constraint under test)
  insert into public.primary_intelligence_links
    (primary_intelligence_id, entity_type, entity_id, relationship_type)
  values (v_pi_id, 'event', v_event_id, 'subject')
  returning id into v_link_id;

  -- Assert the row persists with entity_type='event'
  if not exists (
    select 1 from public.primary_intelligence_links
     where id = v_link_id and entity_type = 'event'
  ) then
    raise exception 'SMOKE FAIL: primary_intelligence_links entity_type=event row not found after insert';
  end if;

  -- Tear down in FK-safe order. The events_audit BEFORE DELETE trigger inserts
  -- into event_changes using the event's space_id, so the event must be deleted
  -- while its space still exists (otherwise the cascade tenant -> spaces -> events
  -- removes the space first and the audit insert hits a FK violation). Delete the
  -- event first, then cascade-delete the tenant (removes space + PI rows), then
  -- the scratch auth user. No trigger state is touched.
  delete from public.events where id = v_event_id;
  delete from public.tenants where id = v_tenant_id;
  delete from auth.users where id = v_user_id;

  raise notice 'SMOKE PASS: primary_intelligence_links entity_type=event accepted by constraint';
end;
$$;

notify pgrst, 'reload schema';
